### ISSUE TITLE
Which VS1053 lib do you use?

### ISSUE THREAD

**Issue by NoNeedForAName123** [bgiraut/SqueezeEsp32#1]
Hi, 
I have tried to compile, but with all VS1053.h file I found on github, i got compile errors.
Which Lib do you use for the VS1053?

Thx

**Comment by bgiraut** [comment]
It can use two differents library for the vs1053 depending of config in config.h 

with vs1053 : 

First : https://github.com/baldram/ESP_VS1053_Library   (#define VS1053_MODULE)
Second : https://github.com/adafruit/Adafruit_VS1053_Library  (#define VS1053_MODULE + #define ADAFRUIT_VS1053) 

It is work better with the first lib

Have a look at  : https://forums.slimdevices.com/showthread.php?109838-SqueezeEsp-The-cheaper-squeezebox-in-the-world

**Comment by NoNeedForAName123** [comment]
Thanks, now I found the problem. In the ESP_VS1053_Library the function write_register() is now 
protected. I 'm not sure what's changed, but I moved the function in the header file (VS1053.h ) to public block an now I can compile successfully ;-)
Thx

**Comment by bgiraut** [comment]
You are right, i have move the function to public too to be able to load flac plugin via a external function but I forget I did it, sorry...

Do you use ESP32 or ESP8266 ?  I had some issues with ESP32 for my part. After 30~40 minutes, the ESP32 no longer receives TCP nor UPD packet. I was able to use ESP8266 during 3 days without any issue.
