### ISSUE TITLE
DEFAULT_LMS_ADDR is never used

### ISSUE THREAD

**Issue by Markus-Be** [bgiraut/SqueezeEsp32#4]
https://github.com/bgiraut/SqueezeEsp32/blob/0216ab41a194de153bc685eb5066ad7cbe7d1008/config.h#L13

I Cant see the point where DEFAULT_LMS_ADDR is used in the code.
Is it a typo or where is this variable is for?

regards

**Comment by bgiraut** [comment]
In the first version the LMS server was hardcoded but i add autodiscovery in the last version so this variable is not used any more. You can use it again if autodiscovery fail on your network.
